### ISSUE TITLE
Problem with urllib2

### ISSUE THREAD

**Issue by Pr0xy671** [grafov/hulk#1]
Your script works, but if you capture the requests it sends using Wireshark, it says, "Connection: close" instead of "Connection: keep-alive". 
The problem is urllib2, they override the Connection header.

Any fix for this? I looked online to try and improve this, but nothing.

**Comment by grafov** [comment]
About original Python utility is better ask its author Barry Shteiman. I am not related to its code and just included the old Python code for reference in my repo.
