### ISSUE TITLE
Python Can't Start New Thread in hulk.py

### ISSUE THREAD

**Issue by mcgregol** [grafov/hulk#13]
I tried running hulk.py and Python gave me an error saying:

`Traceback (most recent call last):
  File "hulk.py", line 153, in <module>
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread`

Also I am new to Go and wondered how to run hulk.go.  Thanks.

**Comment by Marrley** [comment]
you closed the issue how did you make it work?

**Comment by mcgregol** [comment]
I didn't but this project isn't maintained anymore.  You can find other repositories that accomplish the same thing.
