### ISSUE TITLE
Problem running hulk.py

### ISSUE THREAD

**Issue by kayHams** [grafov/hulk#2]
When I run the script with my url for example, "hulk.py www.example.com" I get the following error
Traceback (most recent call last):
   File "hulk.py", line 150, in <module>
      host = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Roland0** [comment]
@kayHams prefix http:// to the beginning of the url, it should solve the issue you are having.

**Comment by grafov** [comment]
About original Python utility is better ask its author Barry Shteiman. I am not related to its code and just included the old Python code for reference in my repo.
