### ISSUE TITLE
What did I do false?

### ISSUE THREAD

**Issue by swordapi** [grafov/hulk#31]
~/hulk $ python3 hulk.py
  File "/data/data/com.termux/files/home/hulk/hulk.py", line 72
    print '---------------------------------------------------'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

PLS HELP THX

**Comment by hiyama283** [comment]
I think it is throwing an error because it does not contain a ()
