### ISSUE TITLE
  File "hulk.py", line 150, in <module>

### ISSUE THREAD

**Issue by gearcapitan** [grafov/hulk#4]
╭──[root Hacked by Gear in ~/root/hulk on master✘✘✘ process!]
╰──± python hulk.py -site www.(thesite).org
-- HULK Attack Started --
Traceback (most recent call last):
  File "hulk.py", line 150, in <module>
    host = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by rohitchormale** [comment]
Hope this regex will solve issue.

**Comment by blackadmini** [comment]
hic.
the same issue with me, 
i tested  python2.6 and python2.7 not working.
/path/to/python -site http://www.(thesite).com "safe"
output:
-- HULK Attack Started --
Traceback (most recent call last):
  File "hulk.py", line 150, in <module>
    host = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by punkjj** [comment]
Same

**Comment by glodinas** [comment]
Can you maybe add how to run the script using go ? 

Yours friendly, 

Glodinas

**Comment by rohitchormale** [comment]
@blackadmini  @punkjj DId you test my pull request ?

**Comment by rohitchormale** [comment]
Also we can catch above error & will not set 'host' header in case of exception.

**Comment by rohitchormale** [comment]
If not, please test & let me know if problem persists. New regex still will not work with ip address. We can add fix by adding 'host' header optionally. I mean if 'site' is ip address, we will not add 'host' header. I will soon send new pull request.

**Comment by BonBonSlick** [comment]
Issue stil lexists for python --version 2.7.17
-- HULK Attack Started --

> Traceback (most recent call last):
>   File "hulk.py", line 150, in <module>
>     host = m.group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by BlackMage2** [comment]
with which Python version does hulk run without error?

**Comment by BonBonSlick** [comment]
@BlackMage2  idk, tried v3 and 2.7

**Comment by swordapi** [comment]
Use: python2 hulk.py <url>

**Comment by cmderx** [comment]
This tool is http specific not https

**Comment by atirrh** [comment]
> Use: python2 hulk.py

Thank you, It worked 👍
